[tool.poetry]
name = "twinLab-Demos"
version = "0.0.0"
description = "A demonstration of twinLab, a toolchain that makes it simple to build machine learning models with uncertainty quantification."
authors = ["Jasper Cantwell <jasper@digilab.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
jupyter = "^1.0.0"
numpy = "^1.24.2"
matplotlib = "^3.7.1"
pandas = "^1.5.3"
# twinlab = {git = "https://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@github.com/digiLab-ai/twinLab.git", branch="mead-twin540-plotting", subdirectory="client/python"}
twinlab = {path = "../twinLab/client/python"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
