[tool.poetry]
name = "twinLab-Demos"
version = "0.1.0"
description = "A demonstration of twinLab, a toolchain that makes it simple to build machine learning models with uncertainty quantification."
authors = ["Jasper Cantwell <jasper@digilab.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
jupyter = "^1.0.0"
matplotlib = "^3.7.1"
numpy = "^1.24.2"
pandas = "<2.0.0"
twinlab = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
