name: Mardown Formatting
on:
  pull_request:
    branches: [dev, main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm install --save-dev --save-exact prettier
      - run: npm run format
